import { modelFor, roles, type Profile, type Role } from '../agent-workflow/models.ts'

export const harnesses = ['codex', 'claude', 'opencode'] as const
export type Harness = (typeof harnesses)[number]
export interface AdapterOptions {
  harness: Harness
  profile: Profile
  engineer?: 'kimi-k3'
}
export interface AdapterFile {
  path: string
  content: string
}

export const ownership = 'Generated by scripts/workflow-adapters.ts'
const descriptions: Record<Role, string> = {
  'coordinator': 'Coordinate an approved issue through the implementation controller.',
  'tech-lead': 'Refine an approved issue and define the implementation plan.',
  'engineer': 'Implement production code within the assigned plan and worktree.',
  'qa': 'Write and execute behavioral tests within the assigned isolated worktree.',
  'reviewer': 'Review the frozen candidate and return findings without editing files.',
  'delivery-lead': 'Analyze run evidence and propose retrospective improvements.',
}

export function validateSupport(options: AdapterOptions): void {
  if (options.harness === 'codex' && options.profile !== 'openai') {
    throw new Error('Codex requires the openai profile; an Anthropic gateway is not configured.')
  }

  if (options.harness === 'claude' && options.profile !== 'anthropic') {
    throw new Error(
      'Claude Code requires the anthropic profile; an OpenAI gateway is not configured.'
    )
  }

  if (options.engineer && options.harness !== 'opencode') {
    throw new Error('The Kimi Engineer requires a supported multiprovider harness: OpenCode V2.')
  }
}

function instructions(role: Role): string {
  return `Read AGENTS.md, docs/agents/implementation-workflow.md, and docs/agents/roles/${role}.md before acting. Follow that canonical role in the controller-assigned worktree and return its report with the requested and effective model/effort receipt, native session ID, and evidence reference.`
}

function readOnly(role: Role): boolean {
  return role === 'reviewer' || role === 'tech-lead'
}

function codex(role: Role, options: AdapterOptions): AdapterFile {
  const preset = modelFor(options.profile, role, options.engineer)

  return {
    path: `.codex/agents/${role}.toml`,
    content: `# ${ownership}\nname = ${JSON.stringify(role)}\ndescription = ${JSON.stringify(descriptions[role])}\nmodel = ${JSON.stringify(preset.model)}\nmodel_reasoning_effort = ${JSON.stringify(preset.effort)}\nsandbox_mode = "${readOnly(role) ? 'read-only' : 'workspace-write'}"\ndeveloper_instructions = ${JSON.stringify(instructions(role))}\n`,
  }
}

function claude(role: Role, options: AdapterOptions): AdapterFile {
  const preset = modelFor(options.profile, role, options.engineer)
  const tools = readOnly(role)
    ? 'Read, Glob, Grep, WebSearch, WebFetch'
    : role === 'coordinator'
      ? 'Read, Glob, Grep, Bash, Agent, AskUserQuestion'
      : 'Read, Glob, Grep, Bash, Edit, Write, WebSearch, WebFetch'

  return {
    path: `.claude/agents/${role}.md`,
    content: `---\nname: ${role}\ndescription: '${descriptions[role]}'\nmodel: ${preset.model}\neffort: ${preset.effort}\ntools: ${tools}\npermissionMode: default\n${role === 'qa' ? 'isolation: worktree\n' : ''}---\n\n<!-- ${ownership} -->\n\n${instructions(role)}\n`,
  }
}

function opencode(role: Role, options: AdapterOptions): AdapterFile {
  const preset = modelFor(options.profile, role, options.engineer)
  const provider = preset.model === 'kimi-k3' ? 'moonshotai' : options.profile
  const permissions = readOnly(role)
    ? [
        { action: '*', resource: '*', effect: 'deny' },
        ...['read', 'glob', 'grep', 'webfetch', 'websearch', 'skill'].map((action) => ({
          action,
          resource: '*',
          effect: 'allow',
        })),
      ]
    : role === 'qa'
      ? [
          { action: 'edit', resource: '*', effect: 'deny' },
          { action: 'edit', resource: '**/tests/**', effect: 'allow' },
          { action: 'shell', resource: '*', effect: 'ask' },
        ]
      : [{ action: 'shell', resource: '*', effect: 'ask' }]
  const rules = permissions
    .map(
      (rule) =>
        `  - action: '${rule.action}'\n    resource: '${rule.resource}'\n    effect: ${rule.effect}`
    )
    .join('\n')

  return {
    path: `.opencode/agents/${role}.md`,
    content: `---\ndescription: '${descriptions[role]}'\nmode: ${role === 'coordinator' ? 'primary' : 'subagent'}\nmodel: ${provider}/${preset.model}#${preset.effort}\npermissions:\n${rules}\n---\n\n<!-- ${ownership} -->\n\n${instructions(role)}\n`,
  }
}

export function renderAdapters(options: AdapterOptions): AdapterFile[] {
  validateSupport(options)
  const render = { codex, claude, opencode }[options.harness]
  const files = roles.map((role) => render(role, options))

  if (options.harness === 'claude') {
    files.push(
      { path: 'CLAUDE.md', content: '@AGENTS.md\n' },
      {
        path: '.claude/skills/implement/SKILL.md',
        content: `---\nname: implement\ndescription: Implement an approved GitHub issue with the shared implementation workflow.\ndisable-model-invocation: true\nargument-hint: '<issue>'\ncontext: fork\nagent: coordinator\nbackground: false\n---\n\n<!-- ${ownership} -->\n\nRead and execute the canonical skill at .agents/skills/implement/SKILL.md with issue argument $ARGUMENTS. Confirm the Coordinator's effective model, effort, and nested delegation capability before starting the controller. Return unresolved Owner questions with the run and native session IDs to the root conversation for relay and resumption on the same configured model and effort.\n`,
      }
    )
  }

  if (options.harness === 'opencode') {
    files.push({
      path: '.opencode/commands/implement.md',
      content: `---\ndescription: Implement an approved GitHub issue with the shared implementation workflow.\nagent: coordinator\n---\n\n<!-- ${ownership} -->\n\nRead and execute the canonical skill at .agents/skills/implement/SKILL.md with issue argument $ARGUMENTS. Confirm the coordinator's effective model and effort before starting the controller.\n`,
    })
  }

  return files
}
